name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: car_com
          MYSQL_ROOT_PASSWORD: mazen2409
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      # Step 3: Run database migrations
      - name: Run migrations
        run: |
          source venv/bin/activate
          python manage.py makemigrations
          python manage.py migrate

      # Step 4: Collect static files
      - name: Collect static files
        run: |
          source venv/bin/activate
          python manage.py collectstatic --noinput

      # Step 5: Run backend tests
      - name: Run backend tests
        run: |
          source venv/bin/activate
          python manage.py test

      # Step 6: Linting and formatting checks
      - name: Run Flake8 for backend
        run: |
          source venv/bin/activate
          flake8 .

      # Step 7: Post results
      - name: Post results
        if: failure()
        run: echo "One or more steps failed"
